### PR TITLE
Add dark mode

### PR DESCRIPTION
**Pull request by 19wintersp**
Also added CSS variables for the Replit brand theme

### CODE REVIEW

**Comment by 19wintersp** [comment]
Solves #13

**Comment by 19wintersp** [comment]
repldm-darkmode

**Comment by Subroutine7901** [comment]
yay!!

**Comment by whippingdot** [comment]
why does no-one merge these commits @19wintersp does 😭

**Comment by Subroutine7901** [comment]
someone needs to merge this

**Comment by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa4** [comment]
MERGE IT PEOPLE

**Comment by Subroutine7901** [comment]
let's not spam here so maybe it has a better chance of being merged
and not spamming means not a ton of messages

**Pull request closed without merging**
